cpufreq: cpu_lp_mask -> cpu_cpu_mask
* When Enable cpu_input_boost building, because topology.h is set to cpu_cpu_mark, we need to change to this
  Otherwise, the following error will occur
  Error:
  drivers/cpufreq/cpu_input_boost.c:61:29: error: use of undeclared identifier 'cpu_lp_mask'; did you mean 'cpu_cpu_mask'?
                if (cpumask_test_cpu(cpu, cpu_lp_mask))
                                          ^~~~~~~~~~~
                                          cpu_cpu_mask

  drivers/cpufreq/cpu_input_boost.c:67:28: error: use of undeclared identifier 'cpu_lp_mask'; did you mean 'cpu_cpu_mask'?
        if (cpumask_test_cpu(cpu, cpu_lp_mask))
                                  ^~~~~~~~~~~
                                  cpu_cpu_mask

  drivers/cpufreq/cpu_input_boost.c:75:28: error: use of undeclared identifier 'cpu_lp_mask'; did you mean 'cpu_cpu_mask'?
        if (cpumask_test_cpu(cpu, cpu_lp_mask))
                                  ^~~~~~~~~~~
                                  cpu_cpu_mask

Signed-off-by: ReallySnow <reallysnow233@gmail.com>
Change-Id: I7e0cba3e6b29b2bbaad3ef725874bb47a5e04a9a